<a href="https://colab.research.google.com/github/onolab-tmu/audio-processing-100-knocks/blob/master/lesson4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# パイソンのNumpyで線形台数

## 先週のリマインド

In [0]:
import numpy as np  # アレー演算と線形台数
import matplotlib.pyplot as plt  # 図
from scipy.io import wavfile  # オーディオファイルの読み込み
from IPython.display import Audio  # ノートブックでのオーディオ再生

## Numpyでアレー演算

`numpy`はアレー演算と線形代数のパッケージ



１次元アレーか**ベクトル**

In [14]:
a_1d = np.array([1, 0.5, -2])
print(a_1d)
print("The shape of this array is", a_1d.shape)

[ 1.   0.5 -2. ]
The shape of this array is (3,)


0から、`N-1`までの整数

In [15]:
N = 10
a = np.arange(0, N)
print(a)

[0 1 2 3 4 5 6 7 8 9]


１から、`N-1`まで、2つずつ

In [16]:
b = np.arange(1, N, 2)
print(b)

[1 3 5 7 9]


`N`から、１まで

In [17]:
c = np.arange(N, 0, -1)
print(c)

[10  9  8  7  6  5  4  3  2  1]


行列・２次元アレーも作れます

In [18]:
a_2d = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)
print(a_2d)
print("The size of this array is", a_2d.shape)

[[1 2 3]
 [4 5 6]]
The size of this array is (2, 3)


示したサイズの`0`入りのアレーも作れます

In [19]:
my_empty_array = np.zeros(10)
print(my_empty_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


２次元も出来ます

In [20]:
# shape は`(4, 3)`, 括弧は大事です！
my_empty_array_2d = np.zeros((4, 3))
print(my_empty_array_2d)
print("The shape of this array is", my_empty_array_2d.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The shape of this array is (4, 3)


同じく、`1`だけのアレーも作れます

In [25]:
my_one_array = np.ones(10)
print("A 1D array of 1s with shape:", my_one_array.shape)
print(my_one_array)

my_one_array_2d = np.ones((2, 4))
print("A 2D array of 1s with shape:", my_one_array_2d.shape)
print(my_one_array_2d)

A 1D array of 1s with shape: (10,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
A 2D array of 1s with shape: (2, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Numpyで線形台数やりましょう！

### 第１問

次の連立方程式をNumpyでときましょう。

$$
  \left\{
    \begin{array}{rcl}
    3 x_1 - 2 x_2 & = & 5 \\
    -7x_1 + 3 x_2 & = & -10
   \end{array}
  \right.
$$

連立方程式は行列の形でかけます
$$
\mathbf{A} \mathbf{x} = \mathbf{b}
$$
なので、最初はNumpyのアレーで行列$\mathbf{A}$とベクトル$\mathbf{b}$を書きます。

出来たら、`x = np.linalg.solve(A, b)`でとく事が出来ます。


In [0]:
A = ...
b = ...
x = np.linalg.solve(A, b)
print(x)